version: '3.7'

services:
  flask:
    build: ./backend
    container_name: flask
    restart: unless-stopped

  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - flask
