service: bpmn-gpt

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: eu-central-1
  memorySize: 128


functions:
  webapp:
    handler: backend.app.handler
    timeout: 30
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'


package:
  patterns:
    - '!node_modules/**'


plugins:
  - serverless-python-requirements


custom:
  pythonRequirements:
    dockerizePip: non-linux